all:
  children:

    linux_rhel:          # every RHEL 9.5 host gets the 'common' role
      children:
        nginx_hosts:
          hosts:
            nginx01:
              ansible_host: 192.168.56.11
        mysql_hosts:
          hosts:
            mysql01:
              ansible_host: 192.168.56.12
        redis_hosts:
          hosts:
            redis01:
              ansible_host: 192.168.56.13
        rabbitmq_hosts:
          hosts:
            rabbitmq01:
              ansible_host: 192.168.56.14
        jvm_app_hosts:
          hosts:
            jvmapp01:
              ansible_host: 192.168.56.15
            jvmapp02:
              ansible_host: 192.168.56.16
        controller:
          hosts:
            controller01:
              ansible_host: 192.168.56.10
              ansible_connection: local

    windows:
      hosts:
        winsrv01:
          ansible_host: 192.168.56.20

# Adjust the 192.168.56.x addresses to match your VMware host-only/NAT network.
